[git_status]
format = '([\[$all_status $ahead_behind\]]($style) )'
all_status = '$conflicted $stashed $deleted $renamed $modified $staged $untracked'
conflicted = 'conflictedğŸš«'
ahead = 'aheadâ¬†ï¸'
behind = 'behindâ¬‡ï¸'
diverged = 'divergedâ†•ï¸'
untracked = 'untrackedâ”'
modified = 'modifiedâœï¸'
staged = 'stagedâœ”ï¸'
renamed = 'renamedğŸ“'
deleted = 'deletedâŒ'
