[conda]
ignore_base = false

[directory]
format = '[$path]($style)[$read_only]($read_only_style) '

[git_branch]
format = 'on [$symbol$branch]($style) '
style = 'bold #CE9178'

[git_status]
format = '[$all_status$ahead_behind]($style) '
conflicted = 'conflictedğŸš«'
ahead = 'â¬†ï¸'
behind = 'â¬‡ï¸'
diverged = 'â†•ï¸'
untracked = 'â”'
modified = 'âœï¸'
staged = 'âœ”ï¸'
renamed = 'ğŸ“'
deleted = 'âŒ'
style = 'white'

