[conda]
ignore_base = false

[directory]
format = '[$path]($style)[$read_only]($read_only_style) '

[git_branch]
format = 'on [$symbol$branch]($style) '
style = 'bold #CE9178'

[git_status]
format = '[$all_status$ahead_behind]($style) '
style = 'white'

[nodejs]
symbol = 'î‰ '
style = 'bold #9ECE6A'
